const book = {
  fileName: state => state.book.fileName,
  menuVisible: state => state.book.menuVisible,
  settingVisible: state => state.book.settingVisible,
  defaultFontSize: state => state.book.defaultFontSize,
  defaultFontFamily: state => state.book.defaultFontFamily,
  fontFamilyVisible: state => state.book.fontFamilyVisible,
  currentBook: state => state.book.currentBook,
  defaultTheme: state => state.book.defaultTheme,
  progress: state => state.book.progress,
  bookAvailable: state => state.book.bookAvailable,
  section: state => state.book.section,
  cover: state => state.book.cover,
  metadata: state => state.book.metadata,
  navigation: state => state.book.navigation,
  offsetY: state => state.book.offsetY,
  isBookmark: state => state.book.isBookmark,
  hotSearchOffsetY: state => state.bookstore.hotSearchOffsetY,
  flapCardVisible: state => state.bookstore.flapCardVisible,
  isEditMode: state => state.bookshelf.isEditMode,
  shelfList: state => state.bookshelf.shelfList,
  shelfSelected: state => state.bookshelf.shelfSelected,
  shelfTitleVisible: state => state.bookshelf.shelfTitleVisible
};
export default book;
